# Generated by Django 4.1.7 on 2023-03-30 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videogame_store', '0003_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='numero',
            new_name='telefone',
        ),
    ]
