# Generated by Django 4.1.7 on 2023-04-01 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('informacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compromisso',
            name='agenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='informacoes.agenda'),
        ),
    ]
